# Generated by Django 3.2.7 on 2021-09-24 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_userplan_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='expiringlink',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 9, 24, 13, 32, 36, 59266)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail_size',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
