# Generated by Django 3.2.7 on 2021-09-26 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20210924_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='thumbnail_size',
        ),
    ]
