# Generated by Django 3.2.11 on 2022-01-19 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_remove_image_thumbnail_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='expiringlink',
            name='height',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='images.imageheight'),
        ),
    ]
